<?php
/**
 * SB_Admin_Bootstrap — one-shot admin-notice that reveals the autogenerated
 * SITE_BRIDGE_SECRET to the site administrator after activation on hosts where
 * editing wp-config.php is not possible.
 *
 * Lifecycle:
 *   1. On activation, SB_Installer::maybe_generate_option_secret() generates a
 *      64-hex-char secret into `wp_options.sb_secret` and sets
 *      `wp_options.sb_secret_show = 1`.
 *   2. While that flag is set AND the current user can `manage_options`, the
 *      notice is rendered on every admin page. It contains the secret, a copy
 *      button, instructions, and a Dismiss button.
 *   3. On Dismiss, an admin-post handler verifies a nonce, deletes the
 *      `sb_secret_show` flag, and redirects back.
 *
 * The notice is also shown on the Plugins screen automatically (via the
 * `after_plugin_row_{plugin}` hook) so the user sees the secret right after
 * clicking "Activate".
 *
 * Security:
 *   - The notice is gated on `manage_options` (i.e. site admins only).
 *   - The Dismiss action is nonce-protected (`sb_dismiss_secret_notice`).
 *   - The secret itself is the same value that signs all subsequent REST
 *     requests, so this is the one and only place where it leaves the server
 *     in plaintext via the wp-admin GUI.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class SB_Admin_Bootstrap {

	const NOTICE_FLAG_OPT = 'sb_secret_show';

	public static function init() {
		if ( ! is_admin() ) {
			return;
		}
		add_action( 'admin_notices',           [ __CLASS__, 'render_notice' ] );
		add_action( 'admin_post_sb_dismiss_secret_notice', [ __CLASS__, 'handle_dismiss' ] );
	}

	public static function render_notice() {
		if ( ! current_user_can( 'manage_options' ) ) {
			return;
		}
		if ( ! get_option( self::NOTICE_FLAG_OPT ) ) {
			return;
		}
		$secret = get_option( SB_Config::OPT_SECRET );
		if ( ! is_string( $secret ) || $secret === '' ) {
			return;
		}
		$using_constant = defined( 'SITE_BRIDGE_SECRET' )
		               && strlen( (string) SITE_BRIDGE_SECRET ) >= SB_Config::MIN_SECRET_BYTES;
		if ( $using_constant ) {
			// User wired up the constant after activation — secret in option is now unused, hide notice.
			delete_option( self::NOTICE_FLAG_OPT );
			return;
		}

		$dismiss_url = wp_nonce_url(
			admin_url( 'admin-post.php?action=sb_dismiss_secret_notice' ),
			'sb_dismiss_secret_notice'
		);
		$site_url = esc_url( home_url( '/' ) );
		$escaped  = esc_attr( $secret );
		?>
		<div class="notice notice-warning" style="padding:14px 18px;">
			<h3 style="margin:0 0 6px 0;">Site Bridge — your HMAC secret was generated</h3>
			<p style="margin:0 0 10px 0;">
				The plugin auto-generated an authentication secret because no
				<code>SITE_BRIDGE_SECRET</code> constant was found in
				<code>wp-config.php</code>. <strong>Copy this secret now</strong> and give it
				to the operator who will be talking to this site's REST API. You will not be
				able to see it again from wp-admin after dismissing this notice.
			</p>
			<p>
				<label for="sb-secret-input"><strong>Secret (64 hex chars):</strong></label><br>
				<input type="text" id="sb-secret-input" readonly value="<?php echo $escaped; ?>"
					style="width:100%;max-width:700px;font-family:monospace;font-size:13px;padding:6px;"
					onclick="this.select();" />
				<button type="button" class="button" style="margin-left:6px;"
					onclick="navigator.clipboard.writeText(document.getElementById('sb-secret-input').value); this.textContent='Copied';">Copy</button>
			</p>
			<p style="margin:10px 0 4px 0;">
				<strong>Add to your Site Bridge client config</strong> (e.g. <code>~/.sb-sites.json</code>):
			</p>
			<pre style="background:#f6f7f7;padding:10px;border:1px solid #ddd;max-width:700px;overflow:auto;"><code>{
  "sites": {
    "this-site": {
      "url": "<?php echo $site_url; ?>",
      "site_bridge_secret": "<?php echo $escaped; ?>"
    }
  }
}</code></pre>
			<p style="margin:10px 0 0 0;">
				For maximum security, copy the secret into <code>wp-config.php</code> as
				<code>define( 'SITE_BRIDGE_SECRET', '…' );</code> and delete the
				<code>sb_secret</code> row from <code>wp_options</code> — this prevents a
				future wp-admin compromise from leaking the secret. See README → Security.
			</p>
			<p style="margin:14px 0 0 0;">
				<a href="<?php echo esc_url( $dismiss_url ); ?>" class="button button-primary">
					I copied it — dismiss this notice
				</a>
			</p>
		</div>
		<?php
	}

	public static function handle_dismiss() {
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_die( 'Forbidden', 403 );
		}
		check_admin_referer( 'sb_dismiss_secret_notice' );
		delete_option( self::NOTICE_FLAG_OPT );
		wp_safe_redirect( admin_url( 'plugins.php' ) );
		exit;
	}
}

SB_Admin_Bootstrap::init();
